server {
    listen 8080;
    server_name formulas.raz formulas.raz.sg;

    root /srv/www/formulas;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    include /etc/nginx/stats-location.conf;
}
